edition="2024"
version = "Two"
hard_tabs=true
imports_granularity="Module"
group_imports="StdExternalCrate"
max_width=80
format_code_in_doc_comments=true
doc_comment_code_block_width=70
unstable_features = true
comment_width=70
